# SPDX-FileCopyrightText: 2026 Damián Búho <damian.buho@proton.me>
#
# SPDX-License-Identifier: MIT

# Auto-generated by generate-deps.sh — do not edit

$(FETCH_PATH)/.reseed-tools.0.3.13.stamp: .container/compile-go/deps/reseed-tools/url.deps .container/compile-go/deps/reseed-tools/version.deps
	M6E_DEPS_STAGE=compile-go .makefile/container/scripts/fetch.sh reseed-tools
	touch $@

.container/compile-go/deps/reseed-tools/hash.deps: $(FETCH_PATH)/.reseed-tools.0.3.13.stamp
	M6E_DEPS_STAGE=compile-go .makefile/container/scripts/update-hash.sh reseed-tools

PREREQUISITES += .container/compile-go/deps/reseed-tools/hash.deps

